library: modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q20-stratifier-city.cql
group:
- type: Patient
  population:
  - expression: InInitialPopulation
  stratifier:
  - code: city
    expression: City
