library: modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q27-stratifier-calculated-bmi.cql
group:
- type: Patient
  population:
  - expression: InInitialPopulation
  stratifier:
  - code: bmi
    expression: Bmi
