library: modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q32-stratifier-underweight.cql
group:
- type: Patient
  population:
  - expression: InInitialPopulation
  stratifier:
  - code: underweight
    expression: Underweight
