version: '3.2'
services:
  store:
    image: "samply/blaze:0.8.0-beta.2"
    environment:
      BASE_URL: "http://localhost:8080"
      DB_DIR: "/app/data/db"
      JAVA_TOOL_OPTIONS: "-Xms2g -Xmx2g -XX:+UseG1GC"
    ports:
    - "8080:8080"
    volumes:
    - "db-data:/app/data"
volumes:
  db-data:
