services:
  keycloak:
    image: "jboss/keycloak:16.1.1@sha256:abdb1aea6c671f61a594af599f63fbe78c9631767886d9030bc774d908422d0a"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/realm.json
    ports:
    - "8090:8080"
    volumes:
    - "${GITHUB_WORKSPACE}/.github/openid-auth-test/realm.json:/tmp/realm.json"

  blaze:
    image: "blaze:latest"
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx2g"
      OPENID_PROVIDER_URL: "http://keycloak:8080/auth/realms/blaze"
    ports:
    - "8080:8080"
    volumes:
    - "blaze-data:/app/data"
    depends_on:
    - keycloak

volumes:
  blaze-data:
