version: '3.7'
services:
  keycloak:
    image: "jboss/keycloak:15.0.2"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/realm.json
    ports:
    - "8090:8080"
    volumes:
    - "${GITHUB_WORKSPACE}/.github/openid-auth-test/realm.json:/tmp/realm.json"

  blaze:
    image: "ghcr.io/samply/blaze:sha-${GITHUB_SHA}"
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx2g"
      OPENID_PROVIDER_URL: "http://keycloak:8080/auth/realms/blaze"
    ports:
    - "8080:8080"
    volumes:
    - "blaze-data:/app/data"
    depends_on:
    - keycloak

volumes:
  blaze-data:
