services:
  keycloak:
    image: "quay.io/keycloak/keycloak:24.0.1"
    command: "start-dev --import-realm"
    volumes:
    - "../../.github/openid-auth-test/realm:/opt/keycloak/data/import"
  blaze:
    image: "samply/blaze:0.24"
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx1g"
      OPENID_PROVIDER_URL: "http://keycloak:8080/realms/blaze"
    ports:
    - "8080:8080"
    volumes:
    - "blaze-data:/app/data"
    depends_on:
    - keycloak
volumes:
  blaze-data:
