version: '3.7'
services:
  keycloak:
    image: "jboss/keycloak:12.0.4"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/realm.json
    ports:
    - "8090:8080"
    volumes:
    - "../../.github/openid-auth-test/realm.json:/tmp/realm.json"
  blaze:
    image: "ghcr.io/samply/blaze:1a90350d0ef932d99cbaab6e7168e3f40216a880"
    environment:
      BASE_URL: "http://localhost:8080"
      JAVA_TOOL_OPTIONS: "-Xmx2g"
      OPENID_PROVIDER_URL: "http://keycloak:8080/auth/realms/blaze"
    ports:
    - "8080:8080"
    volumes:
    - "blaze-data:/app/data"
    depends_on:
    - keycloak
volumes:
  blaze-data:
