services:
  blaze:
    image: "samply/blaze:0.22"
    environment:
      BASE_URL: "http://localhost:8080"
      JAVA_TOOL_OPTIONS: "-Xmx2g"
      ENFORCE_REFERENTIAL_INTEGRITY: "false"
      LOG_LEVEL: "debug"
    ports:
    - "8080:8080"
    volumes:
    - "blaze-data:/app/data"

  hapi:
    image: "hapiproject/hapi:latest"
    ports:
    - "8090:8080"
    environment:
      CATALINA_OPTS: "-Xmx2g"
      HAPI_FHIR_SERVER_ADDRESS: "http://localhost:8090/fhir"
      HAPI_FHIR_SUBSCRIPTION_RESTHOOK_ENABLED: "true"

volumes:
  blaze-data:
